---
apiVersion: v1
kind: Service
metadata:
  name: foodmag-app-sql-service
  namespace: foodmag-app
  labels:
    app: foodmag-app
    env: prod
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
    app: foodmag-app
    env: prod
