apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foodmag-app
  namespace: foodmag-app
spec:
  selector:
    matchLabels:
      app: foodmag-app
      env: prod
  serviceName: foodmag-app
  replicas: 0
  template:
    metadata:
      labels:
        app: foodmag-app
        env: prod
    spec:
      containers:
        - name: foodmag-app-sql
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: foodmag-app-sql
          env:
            - name: POSTGRES_DB
              value: foodmagappdb
            - name: POSTGRES_USER
              value: foodmagapp
            - name: POSTGRES_PASSWORD
              value: foodmagpassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: foodmag-app-sql-pvc
              mountPath: /var/lib/postgresql/data
        - name: foodmag-app-cms
          image: drupal:latest
          ports:
            - containerPort: 30080
              name: foodmag-app-cms
          volumeMounts:
            - name: foodmag-app-cms-pvc
              mountPath: /var/www/html/modules
              subPath: modules
            - name: foodmag-app-cms-pvc
              mountPath: /var/www/html/profiles
              subPath: profiles
            - name: foodmag-app-cms-pvc
              mountPath: /var/www/html/themes
              subPath: themes
  volumeClaimTemplates:
    - metadata:
        name: foodmag-app-sql-pvc
        labels:
          app: foodmag-app
          env: prod
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "storageos-rep-1"
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: foodmag-app-cms-pvc
        labels:
          app: foodmag-app
          env: prod
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "storageos-rep-1"
        resources:
          requests:
            storage: 5Gi