---
apiVersion: v1
kind: Service
metadata:
  name: myshiny-app-db
  namespace: myshiny-app
  labels:
    app: myshiny-app-db
    env: prod
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
    app: myshiny-app-db
    env: prod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myshiny-app-db
  namespace: myshiny-app
  annotations:
    backup.velero.io/backup-volumes: myshiny-app-db-pvc
spec:
  selector:
    matchLabels:
      app: myshiny-app-db
      env: prod
  serviceName: myshiny-app-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: myshiny-app-db
        env: prod
    spec:
      containers:
        - name: myshiny-app-db
          image: postgres
          ports:
            - containerPort: 5432
              name: myshiny-app-db
          env:
            - name: POSTGRES_DB
              value: myshinyappdb
            - name: POSTGRES_USER
              value: myshinyapp
            - name: POSTGRES_PASSWORD
              value: myshinyapppassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: myshiny-app-db-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: myshiny-app-db-pvc
        labels:
          app: myshiny-app-db
          env: prod
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "storageos-rep-1"
        resources:
          requests:
            storage: 1Gi
