---
apiVersion: v1
kind: Service
metadata:
  name: foodmag-app-cms-service
  namespace: foodmag-app
  labels:
    app: foodmag-app
    env: prod
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 30080
  selector:
    app: foodmag-app
    env: prod